# Generated by Django 4.0.2 on 2022-02-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='unnecessary',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
