# Generated by Django 4.0.2 on 2022-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='code_name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (3, 'vkurse.dp.ua'), (4, 'OschadBank'), (5, 'Credit-Agricole'), (6, 'MinFin Avarage')], unique=True),
        ),
    ]
