# Generated by Django 4.0.2 on 2022-02-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_contactus_unnecessary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='unnecessary',
        ),
    ]
