# Generated by Django 4.0.2 on 2022-03-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_Source_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='fitch_ratings',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='social_items',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
