# Generated by Django 4.0.2 on 2022-04-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_null_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro')], max_length=5),
        ),
    ]
